version: 0.2

phases:
  install:
    runtime-versions:
        docker: 18
  pre_build:
    commands:
      - echo Install started on `date`
      - pip install --upgrade awscli==1.18.17
      - echo $(aws sts get-caller-identity) > account_info.json
      - ACCOUNT_ID=$(jq ".Account" account_info.json | sed "s/\"//g")
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - cp ./docker/base/reread/.env.example ./docker/base/reread/.env 

  build:
    commands:
      - echo Build started on `date`
      - docker build -t base_image ./docker/base
      - docker build -t $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/php-fpm-test:$COMMIT_HASH ./docker/php
      - docker build -t $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/nginx-test:$COMMIT_HASH ./docker/web

  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/php-fpm-test:$COMMIT_HASH
      - docker push $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/nginx-test:$COMMIT_HASH
      - IMAGE_TAG="{\"Parameters\":{\"ImageTag\":\"${COMMIT_HASH}\"}}"
      - echo "${IMAGE_TAG}" > imagedetag.json
      - cat imagedetag.json
artifacts:
    files: imagetag.json