version: 0.2

phases:
  pre_build:
    commands:
      - echo Install started on `date`
      - pip install awscli --upgrade
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 786869267134.dkr.ecr.us-west-2.amazonaws.com
      - COMMIT_HASH = $(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

  build:
    commands:
      - echo Build started on `date`
      - cd docker/base
      - docker build -t 786869267134.dkr.ecr.us-west-2.amazonaws.com/base-image:latest .
      - cd ../php
      - docker build -t 786869267134.dkr.ecr.us-west-2.amazonaws.com/php-fpm-test:latest .
      - docker tag 786869267134.dkr.ecr.us-west-2.amazonaws.com/php-fpm-test:latest 786869267134.dkr.ecr.us-west-2.amazonaws.com/php-fpm-test:$COMMIT_HASH

  post_build:
    commands:
      - echo Test completed on `date`
      - docker push 786869267134.dkr.ecr.us-west-2.amazonaws.com/php-fpm-test:latest
      - docker push 786869267134.dkr.ecr.us-west-2.amazonaws.com/php-fpm-test:$COMMIT_HASH
      - IMAGE_DEFINITION_PHP_FPM="{\"imageUri\":\"${COMMIT_HASH}\"}"
      - echo "[${IMAGE_DEFINITION_PHP_FPM}]" > imagedefinition.json

artifacts:
    files: imagedefinition.json