version: 0.2

phases:
  install:
    runtime-versions:
        docker: 18
  pre_build:
    commands:
      - echo Install started on `date`
      - pip install --upgrade awscli==1.18.17
      - $(aws ecr get-login --no-include-email --region us-west-2)
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - cp ./docker/base/reread/.env.example ./docker/base/reread/.env 

  build:
    commands:
      - echo Build started on `date`
      - docker build -t base_image:ver2 ./docker/base
      - docker build -t 786869267134.dkr.ecr.us-west-2.amazonaws.com/php-fpm-test:$COMMIT_HASH ./docker/php
      # - docker tag 786869267134.dkr.ecr.us-west-2.amazonaws.com/php-fpm-test:latest 786869267134.dkr.ecr.us-west-2.amazonaws.com/php-fpm-test:$COMMIT_HASH

  post_build:
    commands:
      - echo Build completed on `date`
      # - docker push 786869267134.dkr.ecr.us-west-2.amazonaws.com/php-fpm-test:latest
      - docker push 786869267134.dkr.ecr.us-west-2.amazonaws.com/php-fpm-test:$COMMIT_HASH
      # - IMAGE_DEFINITION_PHP_FPM="{\"imageUri\":\"${COMMIT_HASH}\"}"
      # - echo "${IMAGE_DEFINITION_PHP_FPM}" > imagedefinition.json
      - IMAGE_DIFINITION="{\"ImageTag\":\"${COMMIT_HASH}\"}"
      - echo "[${IMAGE_DIFINITION}]" > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
    files: imagedefinitions.json